---
development:
  dialect: "sqlite3"
  database: /Users/ytjohn/go/gonetninja/data/gonetninja_development.sqlite

test:
  dialect: "sqlite3"
  database: /Users/ytjohn/go/gonetninja/data/gonetninja_test.sqlite

production:
  dialect: "sqlite3"
  database: /Users/ytjohn/go/gonetninja/data/gonetninja_production.sqlite
